# Generated by Django 4.2.16 on 2024-11-19 20:06
#CODE FROM DANIEL AND VILMER
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_text", models.TextField()),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
