#CODE FROM MIKA AND HASHEM
stages:
  - build-and-test
  - build-and-deploy

variables:
  DOCKER_IMAGE: "pipeline-testing"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""  # Disable TLS verification for `docker:dind`
  GOOGLE_PROJECT_ID: "focused-sprite-443911-p2"
  GOOGLE_REGION: "europe-west4"
  GOOGLE_CLUSTER: "job-cluster"
  DEPLOYED_DOCKER_IMAGE: "gcr.io/focused-sprite-443911-p2/resumeapp"
  DOCKER_TAG: "latest"

build-and-test:
  stage: build-and-test
  tags:
    - docker-build  # Runner tag for the combined build-and-test stage
  services:
    - docker:20.10.10-dind # Use Docker-in-Docker
  script:
    - docker info  # Verify Docker is running and accessible
    - docker build -f Dockerfile.test -t $DOCKER_IMAGE .  # Build the Docker image
    - docker run --rm $DOCKER_IMAGE  # Run the container to execute tests

build-and-deploy:
  stage: build-and-deploy
  image: google/cloud-sdk:latest  # Use the Google Cloud SDK Docker image
  tags:
    - docker-build
  services:
    - docker:20.10.10-dind  # Use Docker-in-Docker
  script:
    # Decode the base64-encoded service account key and store it as gcloud-key.json
    - echo $GCLOUD_SERVICE_KEY | base64 -d > $CI_PROJECT_DIR/gcloud-key.json
    # Authenticate to Google Cloud with the decoded service account key
    - gcloud auth activate-service-account --key-file $CI_PROJECT_DIR/gcloud-key.json
    - gcloud config set project $GOOGLE_PROJECT_ID
    - gcloud config set compute/region $GOOGLE_REGION
    - gcloud container clusters get-credentials $GOOGLE_CLUSTER --region $GOOGLE_REGION
    
    # Build the latest image (production image)
    - docker info
    - docker build --no-cache -f Dockerfile.server . -t $DEPLOYED_DOCKER_IMAGE:$DOCKER_TAG
    - gcloud auth configure-docker
    - docker push $DEPLOYED_DOCKER_IMAGE:$DOCKER_TAG  # Push the image to GCR

    # Deploy to GKE cluster
    - kubectl set image deployment/resumeapp resumeapp=$DEPLOYED_DOCKER_IMAGE:$DOCKER_TAG
    - kubectl apply -f resumeapp-deploy.yaml
    - kubectl rollout restart deployment/resumeapp
  only:
    - tags  # This ensures the deploy stage runs only when a tag is created because we do not want to deploy every commit just test
