name: resume_env
channels:
  - defaults
dependencies:
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.45.3
  - wheel=0.44.0
  - pip:
      - asgiref==3.8.1
      - backports-zoneinfo==0.2.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - django==4.2.16
      - fonttools==4.55.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - numpy==1.24.4
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.16.0
      - sqlparse==0.5.2
      - threadpoolctl==3.5.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - zipp==3.20.2
      - pytest==8.3.4
      - redis==4.6.0
      - django-redis==5.2.0 
